apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: launchconfigurations.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: LaunchConfiguration
    listKind: LaunchConfigurationList
    plural: launchconfigurations
    singular: launchconfiguration
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            associatePublicIPAddress:
              type: boolean
            ebsBlockDevice:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  deviceName:
                    type: string
                  encrypted:
                    type: boolean
                  iops:
                    format: int64
                    type: integer
                  noDevice:
                    type: boolean
                  snapshotID:
                    type: string
                  volumeSize:
                    format: int64
                    type: integer
                  volumeType:
                    type: string
                required:
                - deviceName
                type: object
              type: array
            ebsOptimized:
              type: boolean
            enableMonitoring:
              type: boolean
            ephemeralBlockDevice:
              items:
                properties:
                  deviceName:
                    type: string
                  virtualName:
                    type: string
                required:
                - deviceName
                - virtualName
                type: object
              type: array
            iamInstanceProfile:
              type: string
            id:
              type: string
            imageID:
              type: string
            instanceType:
              type: string
            keyName:
              type: string
            name:
              type: string
            namePrefix:
              type: string
            placementTenancy:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            rootBlockDevice:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  encrypted:
                    type: boolean
                  iops:
                    format: int64
                    type: integer
                  volumeSize:
                    format: int64
                    type: integer
                  volumeType:
                    type: string
                type: object
              maxItems: 1
              type: array
            securityGroups:
              items:
                type: string
              type: array
            spotPrice:
              type: string
            userData:
              type: string
            userDataBase64:
              type: string
            vpcClassicLinkID:
              type: string
            vpcClassicLinkSecurityGroups:
              items:
                type: string
              type: array
          required:
          - imageID
          - instanceType
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                associatePublicIPAddress:
                  type: boolean
                ebsBlockDevice:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      deviceName:
                        type: string
                      encrypted:
                        type: boolean
                      iops:
                        format: int64
                        type: integer
                      noDevice:
                        type: boolean
                      snapshotID:
                        type: string
                      volumeSize:
                        format: int64
                        type: integer
                      volumeType:
                        type: string
                    required:
                    - deviceName
                    type: object
                  type: array
                ebsOptimized:
                  type: boolean
                enableMonitoring:
                  type: boolean
                ephemeralBlockDevice:
                  items:
                    properties:
                      deviceName:
                        type: string
                      virtualName:
                        type: string
                    required:
                    - deviceName
                    - virtualName
                    type: object
                  type: array
                iamInstanceProfile:
                  type: string
                id:
                  type: string
                imageID:
                  type: string
                instanceType:
                  type: string
                keyName:
                  type: string
                name:
                  type: string
                namePrefix:
                  type: string
                placementTenancy:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                rootBlockDevice:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      encrypted:
                        type: boolean
                      iops:
                        format: int64
                        type: integer
                      volumeSize:
                        format: int64
                        type: integer
                      volumeType:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                securityGroups:
                  items:
                    type: string
                  type: array
                spotPrice:
                  type: string
                userData:
                  type: string
                userDataBase64:
                  type: string
                vpcClassicLinkID:
                  type: string
                vpcClassicLinkSecurityGroups:
                  items:
                    type: string
                  type: array
              required:
              - imageID
              - instanceType
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
