apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: monitorautoscalesettings.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: MonitorAutoscaleSetting
    listKind: MonitorAutoscaleSettingList
    plural: monitorautoscalesettings
    singular: monitorautoscalesetting
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            enabled:
              type: boolean
            id:
              type: string
            location:
              type: string
            name:
              type: string
            notification:
              items:
                properties:
                  email:
                    items:
                      properties:
                        customEmails:
                          items:
                            type: string
                          type: array
                        sendToSubscriptionAdministrator:
                          type: boolean
                        sendToSubscriptionCoAdministrator:
                          type: boolean
                      type: object
                    maxItems: 1
                    type: array
                  webhook:
                    items:
                      properties:
                        properties:
                          additionalProperties:
                            type: string
                          type: object
                        serviceURI:
                          type: string
                      required:
                      - serviceURI
                      type: object
                    type: array
                type: object
              maxItems: 1
              type: array
            profile:
              items:
                properties:
                  capacity:
                    items:
                      properties:
                        default:
                          format: int64
                          type: integer
                        maximum:
                          format: int64
                          type: integer
                        minimum:
                          format: int64
                          type: integer
                      required:
                      - default
                      - maximum
                      - minimum
                      type: object
                    maxItems: 1
                    type: array
                  fixedDate:
                    items:
                      properties:
                        end:
                          type: string
                        start:
                          type: string
                        timezone:
                          type: string
                      required:
                      - end
                      - start
                      type: object
                    maxItems: 1
                    type: array
                  name:
                    type: string
                  recurrence:
                    items:
                      properties:
                        days:
                          items:
                            type: string
                          type: array
                        hours:
                          items:
                            format: int64
                            type: integer
                          maxItems: 1
                          type: array
                        minutes:
                          items:
                            format: int64
                            type: integer
                          maxItems: 1
                          type: array
                        timezone:
                          type: string
                      required:
                      - days
                      - hours
                      - minutes
                      type: object
                    maxItems: 1
                    type: array
                  rule:
                    items:
                      properties:
                        metricTrigger:
                          items:
                            properties:
                              metricName:
                                type: string
                              metricResourceID:
                                type: string
                              operator:
                                type: string
                              statistic:
                                type: string
                              threshold:
                                format: float
                                type: number
                              timeAggregation:
                                type: string
                              timeGrain:
                                type: string
                              timeWindow:
                                type: string
                            required:
                            - metricName
                            - metricResourceID
                            - operator
                            - statistic
                            - threshold
                            - timeAggregation
                            - timeGrain
                            - timeWindow
                            type: object
                          maxItems: 1
                          type: array
                        scaleAction:
                          items:
                            properties:
                              cooldown:
                                type: string
                              direction:
                                type: string
                              type:
                                type: string
                              value:
                                format: int64
                                type: integer
                            required:
                            - cooldown
                            - direction
                            - type
                            - value
                            type: object
                          maxItems: 1
                          type: array
                      required:
                      - metricTrigger
                      - scaleAction
                      type: object
                    maxItems: 10
                    type: array
                required:
                - capacity
                - name
                type: object
              maxItems: 20
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            targetResourceID:
              type: string
          required:
          - location
          - name
          - profile
          - providerRef
          - resourceGroupName
          - targetResourceID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                enabled:
                  type: boolean
                id:
                  type: string
                location:
                  type: string
                name:
                  type: string
                notification:
                  items:
                    properties:
                      email:
                        items:
                          properties:
                            customEmails:
                              items:
                                type: string
                              type: array
                            sendToSubscriptionAdministrator:
                              type: boolean
                            sendToSubscriptionCoAdministrator:
                              type: boolean
                          type: object
                        maxItems: 1
                        type: array
                      webhook:
                        items:
                          properties:
                            properties:
                              additionalProperties:
                                type: string
                              type: object
                            serviceURI:
                              type: string
                          required:
                          - serviceURI
                          type: object
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                profile:
                  items:
                    properties:
                      capacity:
                        items:
                          properties:
                            default:
                              format: int64
                              type: integer
                            maximum:
                              format: int64
                              type: integer
                            minimum:
                              format: int64
                              type: integer
                          required:
                          - default
                          - maximum
                          - minimum
                          type: object
                        maxItems: 1
                        type: array
                      fixedDate:
                        items:
                          properties:
                            end:
                              type: string
                            start:
                              type: string
                            timezone:
                              type: string
                          required:
                          - end
                          - start
                          type: object
                        maxItems: 1
                        type: array
                      name:
                        type: string
                      recurrence:
                        items:
                          properties:
                            days:
                              items:
                                type: string
                              type: array
                            hours:
                              items:
                                format: int64
                                type: integer
                              maxItems: 1
                              type: array
                            minutes:
                              items:
                                format: int64
                                type: integer
                              maxItems: 1
                              type: array
                            timezone:
                              type: string
                          required:
                          - days
                          - hours
                          - minutes
                          type: object
                        maxItems: 1
                        type: array
                      rule:
                        items:
                          properties:
                            metricTrigger:
                              items:
                                properties:
                                  metricName:
                                    type: string
                                  metricResourceID:
                                    type: string
                                  operator:
                                    type: string
                                  statistic:
                                    type: string
                                  threshold:
                                    format: float
                                    type: number
                                  timeAggregation:
                                    type: string
                                  timeGrain:
                                    type: string
                                  timeWindow:
                                    type: string
                                required:
                                - metricName
                                - metricResourceID
                                - operator
                                - statistic
                                - threshold
                                - timeAggregation
                                - timeGrain
                                - timeWindow
                                type: object
                              maxItems: 1
                              type: array
                            scaleAction:
                              items:
                                properties:
                                  cooldown:
                                    type: string
                                  direction:
                                    type: string
                                  type:
                                    type: string
                                  value:
                                    format: int64
                                    type: integer
                                required:
                                - cooldown
                                - direction
                                - type
                                - value
                                type: object
                              maxItems: 1
                              type: array
                          required:
                          - metricTrigger
                          - scaleAction
                          type: object
                        maxItems: 10
                        type: array
                    required:
                    - capacity
                    - name
                    type: object
                  maxItems: 20
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                targetResourceID:
                  type: string
              required:
              - location
              - name
              - profile
              - providerRef
              - resourceGroupName
              - targetResourceID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
