apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: opsworksapplications.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: OpsworksApplication
    listKind: OpsworksApplicationList
    plural: opsworksapplications
    singular: opsworksapplication
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appSource:
              items:
                properties:
                  revision:
                    type: string
                  sshKey:
                    type: string
                  type:
                    type: string
                  url:
                    type: string
                  username:
                    type: string
                required:
                - type
                type: object
              type: array
            autoBundleOnDeploy:
              type: string
            awsFlowRubySettings:
              type: string
            dataSourceArn:
              type: string
            dataSourceDatabaseName:
              type: string
            dataSourceType:
              type: string
            description:
              type: string
            documentRoot:
              type: string
            domains:
              items:
                type: string
              type: array
            enableSSL:
              type: boolean
            environment:
              items:
                properties:
                  key:
                    type: string
                  secure:
                    type: boolean
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
            id:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            railsEnv:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            shortName:
              type: string
            sslConfiguration:
              items:
                properties:
                  certificate:
                    type: string
                  chain:
                    type: string
                required:
                - certificate
                type: object
              type: array
            stackID:
              type: string
            type:
              type: string
          required:
          - name
          - providerRef
          - stackID
          - type
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                appSource:
                  items:
                    properties:
                      revision:
                        type: string
                      sshKey:
                        type: string
                      type:
                        type: string
                      url:
                        type: string
                      username:
                        type: string
                    required:
                    - type
                    type: object
                  type: array
                autoBundleOnDeploy:
                  type: string
                awsFlowRubySettings:
                  type: string
                dataSourceArn:
                  type: string
                dataSourceDatabaseName:
                  type: string
                dataSourceType:
                  type: string
                description:
                  type: string
                documentRoot:
                  type: string
                domains:
                  items:
                    type: string
                  type: array
                enableSSL:
                  type: boolean
                environment:
                  items:
                    properties:
                      key:
                        type: string
                      secure:
                        type: boolean
                      value:
                        type: string
                    required:
                    - key
                    - value
                    type: object
                  type: array
                id:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                railsEnv:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                shortName:
                  type: string
                sslConfiguration:
                  items:
                    properties:
                      certificate:
                        type: string
                      chain:
                        type: string
                    required:
                    - certificate
                    type: object
                  type: array
                stackID:
                  type: string
                type:
                  type: string
              required:
              - name
              - providerRef
              - stackID
              - type
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
